"$schema" = 'https://starship.rs/config-schema.json'

[character]
success_symbol = '[λ](bold green)'
error_symbol = '[λ](bold red)'

[aws]
disabled = true
format = 'on [$symbol$region]($style) '
style = 'blue'

[aws.region_aliases]
ap-southeast-2 = 'au'
us-east-1 = 'va'
ap-northeast-1 = 'jp'

[hostname]
ssh_symbol = ""
format = '$ssh_symbol $hostname '

[gcloud]
disabled = true
